name: Build and run unit tests

on:
  push:
    branches: dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use
  PROJECT_PATH: './Website'
  PROJECT_NAME: 'Test'
  TEST_FILENAME: 'TestResults.md'
  DEPLOYMENT_RESOURCE_GROUP_NAME: 'AutoTest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job.  You can easily have multiple jobs but they run in separate virtual
  # machines and don't share an environment, so it's harder to split up things into say, build and test jobs
  build_and_test:
    name: Build all .NET projects then run tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environments are where we store secrets, all secrets in this environment can be accessed by this action
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    # They are executed in order
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: azure/CLI@v1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      # confirm we can access secrets within an environment
      - name: decrypt deployment config file
        env:
          CONFIG_SECRET: ${{ secrets.CONFIG_SECRET }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$CONFIG_SECRET" --output $HOME/secrets/config.json config/config.json.gpg
        
      # Build the selected project
      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          dotnet restore
          dotnet build

      # Test the selected project
      - name: Run unit tests on the main project
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet test --no-restore --no-build ${{ env.PROJECT_NAME }} --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.TEST_FILENAME}};"
      
      # upload test report as build artifact (unfortunately it doesn't display it nicely)
      - name: Upload test report as build artifact
        uses: actions/upload-artifact@v3
        # Use always() to always run this step to publish test results even when there are test failures
        if: ${{always()}}
        with:
          name: 'NUnit test run'
          path: ${{github.workspace}}/${{env.TEST_FILENAME}}
      
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup python packages so we can run deploytool
        working-directory: scripts
        run: pip install -r requirements.txt


      # Deploy databases to Azure
      - name: Run deploytool to create databases on Azure
        working-directory: scripts
        run: python deploytool.py --dry-run $HOME/secrets/config.json $DEPLOYMENT_RESOURCE_GROUP_NAME create-db
      
